# Homebrew formula for ctxd-code.
#
# Generated by .github/workflows/release.yml from
# homebrew/ctxd-code.rb.tmpl on every v* tag and pushed to
# keeprlabs/homebrew-tap/Formula/ctxd-code.rb.

class CtxdCode < Formula
  desc "Capture every Claude Code, Cursor, and Codex session into ctxd"
  homepage "https://github.com/keeprlabs/ctxd-code"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/keeprlabs/ctxd-code/releases/download/v#{version}/ctxd-code-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0e919fd7d1debe53a6834770a13ec52b1a888a5ff5205234c90ccada8937222c"
    end
    on_intel do
      url "https://github.com/keeprlabs/ctxd-code/releases/download/v#{version}/ctxd-code-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "3580f817ecbd410fba7582487f3e4ae57ae8654c680479e97823c3a55096c230"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/keeprlabs/ctxd-code/releases/download/v#{version}/ctxd-code-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1424ac27ad40f0cb2c91fd7dd863a36706d26795e1ea2aa13f00deefae85a6b5"
    end
    on_intel do
      url "https://github.com/keeprlabs/ctxd-code/releases/download/v#{version}/ctxd-code-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "054b39003caa921bb69bdd4019a67a810cebc3afb8c70bd2eefeb2d039035f48"
    end
  end

  depends_on "keeprlabs/tap/ctxd"

  def install
    bin.install "ctxd-code-#{version}-#{stage_target}/ctxd-code"
    doc.install "ctxd-code-#{version}-#{stage_target}/README.md",
                "ctxd-code-#{version}-#{stage_target}/LICENSE"
  end

  def stage_target
    if OS.mac?
      Hardware::CPU.arm? ? "aarch64-apple-darwin" : "x86_64-apple-darwin"
    else
      Hardware::CPU.arm? ? "aarch64-unknown-linux-gnu" : "x86_64-unknown-linux-gnu"
    end
  end

  test do
    assert_match "ctxd-code", shell_output("#{bin}/ctxd-code --version")
  end
end
